;;; protocols.lisp -- Wayland stable protocols implementations
;;;
;;; Copyright (c) 2022 Samuel Hunter.
;;; All rights reserved.

;; This file is loaded before all other protocols, as other protocols are
;; dependent on wayland core types (such as wl-output, wl-buffer, etc).
;; Separating them out by file prevents symbol conflicts, since evaluating
;; (export ...) at exec-time generated by WL-INCLUDE happens after interning
;; symbols at macro-expansion time.

(in-package #:xyz.shunter.wayflan.client)

(xyz.shunter.wayflan.autowrap:wl-include
  #.(merge-pathnames #P"protocols/wayland.xml"
                     (asdf:system-source-directory '#:wayflan))
  :exclude-defclasses (wl-display)
  :export t)
