[
{ "tag": "struct", "ns": 0, "name": "sockaddr_un", "id": 0, "location": "/home/russky/Documents/Programs/wayflan/sockets/spec/socket.h:9:16", "bit-size": 0, "bit-alignment": 0, "fields": [] },
{ "tag": "typedef", "ns": 0, "name": "sockaddr_un", "location": "/home/russky/Documents/Programs/wayflan/sockets/spec/socket.h:9:28", "type": { "tag": "struct", "ns": 0, "name": "sockaddr_un", "id": 0, "location": "/home/russky/Documents/Programs/wayflan/sockets/spec/socket.h:9:16", "bit-size": 0, "bit-alignment": 0, "fields": [] } },
{ "tag": "struct", "ns": 0, "name": "iovec", "id": 0, "location": "/home/russky/Documents/Programs/wayflan/sockets/spec/socket.h:10:16", "bit-size": 0, "bit-alignment": 0, "fields": [] },
{ "tag": "typedef", "ns": 0, "name": "iovec", "location": "/home/russky/Documents/Programs/wayflan/sockets/spec/socket.h:10:22", "type": { "tag": "struct", "ns": 0, "name": "iovec", "id": 0, "location": "/home/russky/Documents/Programs/wayflan/sockets/spec/socket.h:10:16", "bit-size": 0, "bit-alignment": 0, "fields": [] } },
{ "tag": "struct", "ns": 0, "name": "cmsghdr", "id": 0, "location": "/home/russky/Documents/Programs/wayflan/sockets/spec/socket.h:11:16", "bit-size": 0, "bit-alignment": 0, "fields": [] },
{ "tag": "typedef", "ns": 0, "name": "cmsghdr", "location": "/home/russky/Documents/Programs/wayflan/sockets/spec/socket.h:11:24", "type": { "tag": "struct", "ns": 0, "name": "cmsghdr", "id": 0, "location": "/home/russky/Documents/Programs/wayflan/sockets/spec/socket.h:11:16", "bit-size": 0, "bit-alignment": 0, "fields": [] } },
{ "tag": "struct", "ns": 0, "name": "msghdr", "id": 0, "location": "/home/russky/Documents/Programs/wayflan/sockets/spec/socket.h:12:16", "bit-size": 0, "bit-alignment": 0, "fields": [] },
{ "tag": "typedef", "ns": 0, "name": "msghdr", "location": "/home/russky/Documents/Programs/wayflan/sockets/spec/socket.h:12:23", "type": { "tag": "struct", "ns": 0, "name": "msghdr", "id": 0, "location": "/home/russky/Documents/Programs/wayflan/sockets/spec/socket.h:12:16", "bit-size": 0, "bit-alignment": 0, "fields": [] } }
]
